version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quotes  # Default database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Persist database data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Run initial SQL

volumes:
  mysql-data:
